/* eslint-disable */
// The tokens generated by the sidecar must carry the component identity (JIT-16349),
// so the selector can bind the websocket connection to this component only.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { describe, it } = require('node:test');

const jsonwebtoken = require('jsonwebtoken');

const AsapRequest = require('../dist/service/asap_request').default;

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });
const signingKey = Buffer.from(privateKey.export({ type: 'pkcs1', format: 'pem' }));
const publicKeyPem = publicKey.export({ type: 'spki', format: 'pem' });

function makeAsapRequest(overrides = {}) {
    return new AsapRequest({
        signingKey,
        asapJwtIss: 'jitsi-component-sidecar',
        asapJwtAud: 'jitsi-component-selector',
        asapJwtKid: 'jitsi/test',
        ...overrides
    });
}

function verify(token) {
    return jsonwebtoken.verify(token, publicKeyPem, {
        algorithms: [ 'RS256' ],
        issuer: 'jitsi-component-sidecar',
        audience: 'jitsi-component-selector',
        complete: true
    });
}

describe('sidecar tokens carry the component identity', () => {
    it('puts the componentKey in the sub claim by default', () => {
        const { header, payload } = verify(makeAsapRequest({ componentKey: 'jibri-42-183-93' }).authToken());

        assert.equal(header.kid, 'jitsi/test');
        assert.equal(payload.sub, 'jibri-42-183-93');
    });

    it('supports a custom componentKey claim', () => {
        const { payload } = verify(makeAsapRequest({
            componentKey: 'jibri-42-183-93',
            componentKeyClaim: 'componentKey'
        }).authToken());

        assert.equal(payload.componentKey, 'jibri-42-183-93');
        assert.equal(payload.sub, undefined);
    });

    it('still generates a valid token without a componentKey', () => {
        const { payload } = verify(makeAsapRequest().authToken());

        assert.equal(payload.sub, undefined);
        assert.equal(payload.iss, 'jitsi-component-sidecar');
    });

    it('caches the token', () => {
        const asapRequest = makeAsapRequest({ componentKey: 'jibri-42-183-93' });

        assert.equal(asapRequest.authToken(), asapRequest.authToken());
    });
});
